version: "3"
   
services:
  db:
    image: postgres:16.2-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dsy
    ports:
      - 5434:5432

  app:
    container_name: dsy_app
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8001
    ports:
      - 8001:8001
    volumes:
      - ./:/app/
    depends_on:
      - db
    env_file:
      - .env