# Generated by Django 4.0.5 on 2025-03-08 06:18

import base.helpers.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proejct_no', models.CharField(max_length=15, unique=True)),
                ('proejct_name', models.CharField(max_length=150)),
                ('proejct_type', models.CharField(choices=[('new_building', 'New Building'), ('repair', 'Repair'), ('completed', 'Completed')], max_length=25)),
                ('publish_date', models.DateTimeField()),
                ('length', models.CharField(max_length=25)),
                ('breadth', models.CharField(max_length=25)),
                ('depth', models.CharField(max_length=25)),
                ('draft', models.CharField(max_length=25)),
                ('max_speed', models.CharField(max_length=25)),
                ('special_feature', models.TextField()),
                ('project_photo', models.ImageField(help_text='File size should be less than 3mb(.doc/.pdf)', upload_to='project/', validators=[base.helpers.validators.file_size_validator])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMachinery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_engine', models.CharField(max_length=150)),
                ('engine_power', models.CharField(max_length=80)),
                ('engine_quantity', models.IntegerField()),
                ('main_dg', models.CharField(max_length=150)),
                ('dg_power', models.CharField(max_length=80)),
                ('dg_quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='page.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('classification', models.CharField(max_length=25)),
                ('client', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='page.project')),
            ],
        ),
    ]
