# Generated by Django 4.0.5 on 2025-03-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='proejct_category',
            field=models.CharField(choices=[('on_going', 'On Going'), ('completed', 'Completed')], default='on_going', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='proejct_type',
            field=models.CharField(choices=[('new_building', 'New Building'), ('repair', 'Repair')], max_length=25),
        ),
    ]
