# Generated by Django 4.0.5 on 2025-03-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_contactus_teammember_jobpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Benifit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EducationalRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Responsibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='additional_requirements',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='benifits',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='educational_requirements',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='experience_requirements',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='job_responsibilities',
        ),
    ]
