# Generated by Django 4.0.5 on 2025-03-10 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('page', '0006_jobpost_additional_requirements_jobpost_benifits_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DockingCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vessel_name', models.CharField(max_length=100)),
                ('ength', models.CharField(max_length=25)),
                ('breadth', models.CharField(max_length=25)),
                ('depth', models.CharField(max_length=25)),
                ('registration_no', models.CharField(max_length=25)),
                ('issue_date', models.DateField()),
                ('certificate_no', models.CharField(blank=True, max_length=25, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
