# Generated by Django 4.0.5 on 2025-03-10 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_dockingcertificate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dockingcertificate',
            old_name='ength',
            new_name='length',
        ),
    ]
