# Generated by Django 4.0.5 on 2024-05-20 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimplifyBaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('simplifybasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ta_device.simplifybasemodel')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
            bases=('ta_device.simplifybasemodel',),
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('simplifybasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ta_device.simplifybasemodel')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ('-created_at',),
            },
            bases=('ta_device.simplifybasemodel',),
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('simplifybasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ta_device.simplifybasemodel')),
                ('name', models.CharField(max_length=30)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sat', models.BooleanField(default=False)),
                ('sun', models.BooleanField(default=False)),
                ('mon', models.BooleanField(default=False)),
                ('tue', models.BooleanField(default=False)),
                ('wed', models.BooleanField(default=False)),
                ('thu', models.BooleanField(default=False)),
                ('fri', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-created_at',),
            },
            bases=('ta_device.simplifybasemodel',),
        ),
        migrations.CreateModel(
            name='TADevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_name', models.CharField(max_length=100)),
                ('ip_address', models.CharField(max_length=100, unique=True)),
                ('device_status', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_id_no', models.IntegerField()),
                ('emp_id_no', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('designation', models.CharField(max_length=150)),
                ('card_no', models.IntegerField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_device', to='ta_device.tadevice')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('punch_in_date', models.DateField()),
                ('punch_in_time', models.TimeField()),
                ('punch_out_date', models.DateField(blank=True, null=True)),
                ('punch_out_time', models.TimeField(blank=True, null=True)),
                ('working_hour', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('status', models.BooleanField(default=False)),
                ('late_count', models.TimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attend_emp', to='ta_device.employee')),
                ('punch_in_device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_in', to='ta_device.tadevice')),
                ('punch_out_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_out', to='ta_device.tadevice')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('simplifybasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ta_device.simplifybasemodel')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('department_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selction_list', to='ta_device.department')),
            ],
            options={
                'ordering': ('-created_at',),
            },
            bases=('ta_device.simplifybasemodel',),
        ),
        migrations.CreateModel(
            name='HolidayCalender',
            fields=[
                ('simplifybasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ta_device.simplifybasemodel')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('total_day', models.DecimalField(decimal_places=2, max_digits=5)),
                ('year', models.IntegerField()),
                ('holiday_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holiday_calender', to='ta_device.holiday')),
            ],
            options={
                'ordering': ('-created_at',),
            },
            bases=('ta_device.simplifybasemodel',),
        ),
        migrations.AddField(
            model_name='employee',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_list', to='ta_device.section'),
        ),
        migrations.AddField(
            model_name='employee',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_employee', to='ta_device.shift'),
        ),
        migrations.CreateModel(
            name='DeviceControl',
            fields=[
                ('simplifybasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ta_device.simplifybasemodel')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_control', to='ta_device.tadevice')),
            ],
            options={
                'ordering': ('-created_at',),
            },
            bases=('ta_device.simplifybasemodel',),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('emp', 'punch_in_date'), name='unique_emp_date'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('device', 'emp_id_no'), name='unique_device_emp'),
        ),
    ]
