# Generated by Django 4.0.5 on 2024-05-21 09:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ta_device', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='duration',
        ),
        migrations.AddField(
            model_name='shift',
            name='shift_duration',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
