# Generated by Django 4.0.5 on 2024-05-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_device', '0002_remove_shift_duration_shift_shift_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='working_hour',
        ),
        migrations.AddField(
            model_name='attendance',
            name='duration',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
