# Generated by Django 4.0.5 on 2024-05-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_device', '0003_remove_attendance_working_hour_attendance_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id_no',
            field=models.CharField(max_length=50),
        ),
    ]
