# Generated by Django 4.0.5 on 2024-05-20 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_active_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='user/default.png', upload_to='user_photo'),
        ),
    ]
